name: mazdoor_online_labor_app
description: Companioin APP for MAZDOORONLINE FOR LABOR

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  google_maps_flutter: ^2.2.5
  flutter_config: ^2.0.0
  dio: ^5.1.2
  geolocator: ^9.0.2
  provider: ^6.0.5
  flutter_easyloading: ^3.0.5
  flutter_polyline_points: ^1.0.0
  slider_button: ^2.0.0
  intl: ^0.18.1
  location:
    git:
      url: https://github.com/fairuzmn/flutterlocation.git
      ref: location-v5.5.0.0-dev.9-fix
      path: packages/location

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo.png
    - assets/images/welcome_screen1.png
    - assets/images/welcome_screen2.png
    - assets/images/welcome_screen3.png
    - assets/images/bottom-cloud.png
